/**
 * Gleam Services - API Client
 * Manages secure communications with Make.com, Stripe, and Google reCAPTCHA.
 * Completely decoupled from the UI and pricing math.
 */

const ApiClient = {
    // --- CONFIGURATION ---
    config: {
        // Replace this with the URL generated by your Make.com Custom Webhook module
        makeWebhookUrl: 'https://hook.us1.make.com/YOUR_UNIQUE_WEBHOOK_ID', 
        
        // Replace this with your Google reCAPTCHA v3 Site Key
        recaptchaSiteKey: 'YOUR_V3_SITE_KEY', 
        
        bookingHubUrl: 'https://getgleaming.com/online-booking'
    },

    // --- 1. SECURE WEBHOOK FETCH (Phase 4.1) ---
    /**
     * Pings reCAPTCHA for a token, bundles the state data, and sends it to Make.com.
     */
    async fetchDigitalTwinEstimate() {
        try {
            // 1. Get the reCAPTCHA token to prove it's a human
            const token = await this.getRecaptchaToken('submit_estimate');
            
            // 2. Grab the clean data object from our StateManager
            const currentState = window.StateManager.state;
            
            // 3. Assemble the payload mapped to the Make.com Data Contract
            const payload = {
                recaptcha_token: token,
                customer_type: currentState.customerType,
                zip_code: currentState.zipCode,
                sqft: currentState.sqft,
                stories: currentState.stories,
                basement: currentState.basement,
                skylights: currentState.skylights,
                history: currentState.history,
                selected_services: Array.from(currentState.selectedServices),
                
                // We also pass the baseline math we calculated in the frontend
                baseline_estimate: currentState.estimateResult 
            };

            // 4. Send the secure fetch() call to the Make.com Webhook
            const response = await fetch(this.config.makeWebhookUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            // Return the finalized "Digital Twin" JSON from Make.com (Phase 3.5)
            const aiPayload = await response.json();
            return aiPayload;

        } catch (error) {
            console.error("Make.com API Error:", error);
            // Returning null allows the UI to trigger the low-confidence escape hatch
            return null; 
        }
    },

    // --- 2. THE BOUNCER (reCAPTCHA Wrapper) ---
    /**
     * Wraps the invisible reCAPTCHA execution in a clean Promise.
     */
    getRecaptchaToken(actionName) {
        return new Promise((resolve, reject) => {
            if (typeof grecaptcha === 'undefined') {
                reject("reCAPTCHA script not loaded properly.");
                return;
            }
            grecaptcha.ready(() => {
                grecaptcha.execute(this.config.recaptchaSiteKey, { action: actionName })
                    .then((token) => resolve(token))
                    .catch((err) => reject(err));
            });
        });
    },

    // --- 3. CROSS-WIDGET STATE HANDOFF (Phase 4.5.3) ---
    /**
     * Securely transfers the finalized data from the Estimator to the Booking Hub.
     */
    redirectToBookingHub(finalPayload) {
        // Method A: Save to sessionStorage so the next page can read it instantly
        sessionStorage.setItem('gleam_digital_twin', JSON.stringify(finalPayload));
        
        // Method B: Base64 encode it into the URL as a backup transfer method
        const encodedPayload = btoa(JSON.stringify(finalPayload));
        const redirectUrl = `${this.config.bookingHubUrl}?data=${encodeURIComponent(encodedPayload)}`;
        
        // Execute redirect
        window.location.href = redirectUrl;
    }
};

// Expose to window for UI usage
window.ApiClient = ApiClient;